name: E2E Tests

on:
  - push
jobs:
   e2e:
      runs-on: ubuntu-latest
      if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"
      strategy:
         fail-fast: false
         matrix:
            containers: [ 1 ]
      steps:
         - name: Checkout
           uses: actions/checkout@v2

         - uses: actions/setup-node@v1
           with:
             node-version: 12.x
         - name: End-to-End tests
           uses: cypress-io/github-action@v2
           with:
              start: yarn cy:start
              wait-on: 'http://localhost:3000'
              wait-on-timeout: 300
              record: true
              parallel: true
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              CYPRESS_dhis2BaseUrl: ${{secrets.CYPRESS_DHIS2_BASE_URL}}
              CYPRESS_dhis2ApiVersion: ${{secrets.CYPRESS_DHIS2_API_VERSION}}
              CYPRESS_networkMode: stub
